image: maven:latest

include:
  #stages
  - project: 'dfkzbt/gitlab-ci-utility'
    ref: master
    file: 'gitlab-ci/pipeline/stages-generic.yml'
  # debug
  - project: 'dfkzbt/gitlab-ci-utility'
    ref: master
    file: 'gitlab-ci/pipeline/debug-generic.yml'
  # report templates
  - project: 'dfkzbt/gitlab-ci-utility'
    ref: master
    file: 'gitlab-ci/pipeline/junit-maven-reports-generic.yml'
  # build - maven
  - project: 'dfkzbt/gitlab-ci-utility'
    ref: master
    file: 'gitlab-ci/pipeline/generic-build-maven.yml'
  # production push - external maven packages
  - project: 'dfkzbt/gitlab-ci-utility'
    ref: master
    file: 'gitlab-ci/pipeline/generic-maven-production-packages-external.yml'


variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"


cache:
  paths:
    - .m2/repository/
#    - target/
#    - ./**/target/

#
